name: Automatic deploy!

on:
  workflow_run:
    workflows: ['Deployment Pipeline']
    types: [completed]
    branches: [main]

jobs:
  on-success:
    runs-on: ubuntu-20.04
    if: |
      github.event_name == 'push' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    steps:
      - name: event name
        run: echo ${{ github.event_name }}
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Result
        run: echo "Application deployed"
  on-failure:
    runs-on: ubuntu-20.04
    if: |
      github.event_name == 'push' &&
      github.event.workflow_run.conclusion == 'failure' &&
      github.event.workflow_run.head_branch == 'main'
    steps:
      - name: event name
        run: echo ${{ github.event_name }}
      - name: Result
        run: echo "Deployment Pipeline failed"
