name: Automatic deploy!

on:
  workflow_run:
    workflows: ['Deployment Pipeline']
    types: [completed]
    branches: [main]

env:
  CONDITION: ${{ contains(github.event.workflow_run.head_commit.message, '#skip') }}

jobs:
  run_environment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.workflow_run.head_commit) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.workflow_run.head_commit.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: Condition resolution
        run: echo ${{ env.CONDITION }}
  on-success:
    if: ${{ (github.event.workflow_run.conclusion == 'success') && (github.env.CONDITION == 'false') }}
    runs-on: ubuntu-20.04
    steps:
      - name: event name
        run: echo ${{ github.event_name }}
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Result
        run: echo "Application deployed"
  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-20.04
    steps:
      - name: event name
        run: echo ${{ github.event_name }}
      - name: Result
        run: echo "Deployment Pipeline failed"
  on-skip:
    if: ${{ github.env.CONDITION == 'true' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Skip condition true
        run: echo ${{ env.CONDITION }}
