name: Automatic deploy!

on: 
  workflow_run:
    workflows: ["Hello World!", "Deployment Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
