name: Automatic deploy!

on:
  workflow_run:
    workflows: ['Deployment Pipeline']
    types: [completed]
    branches: [main]

env:
  CONDITION: ${{ contains(join(github.event.commits.*.message, ','), '#skip') }}

jobs:
  on-success:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: event name
        run: echo ${{ github.event_name }}
      - name: Trigger deployment
        if: ${{ github.env.CONDITION == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Result
        run: echo "Application deployed"
  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-20.04
    steps:
      - name: event name
        run: echo ${{ github.event_name }}
      - name: Result
        run: echo "Deployment Pipeline failed"
  on-skip:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: event name
        if: ${{ github.env.CONDITION == 'true' }}
        run: echo 'Deployment will be skipped'
