name: Automatic deploy!

on: 
  check_suite:
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
